apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: trading-simulator-staging
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/gerardsegismundo/Project-Sentinel.git
    targetRevision: HEAD
    path: helm/banking-app
    helm:
      valueFiles:
        - values-staging.yaml
      parameters:
        - name: image.tag
          value: latest-staging
  destination:
    server: https://kubernetes.default.svc
    namespace: banking
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 3
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
