---
all:
  hosts:
    localhost:
      ansible_connection: local
  children:
    eks_clusters:
      hosts:
        project-sentinel-dev:
          eks_cluster_name: project-sentinel-dev
          environment: dev
          aws_region: us-east-1
